### ISSUE TITLE
新角色、难度配色，以及自定义配色预设

### ISSUE THREAD

**Issue by Yanstory** [Horiztar/Cylheim-Windows#10]
目前CytusⅡ已加入新角色Amiya和新难度DREAM，这两个的配色模板还没有实装到Cylheim里

此外有没有方法保存自定义的配色预设供以后制谱时快速调用呢？

**Comment by Horiztar** [comment]
新角色和新难度会在后续版本跟进，保存自定义配色仍在考虑中。

**Comment by Horiztar** [comment]
3.1版本将会实装以上提到的新内容和功能。
