### ISSUE TITLE
3.0版本延迟问题

### ISSUE THREAD

**Issue by 1oon9** [Horiztar/Cylheim-Windows#11]
输入延迟后没有立即生效，需要暂停再播放或者从头播放，或者根本不起作用。

**Comment by Horiztar** [comment]
延迟输入框的值无法提交的问题已知，会在后续版本进行修复，可以使用滚轮调整延迟值或者在手动输入以后点击播放来提交输入值。但需要注意本身不支持在播放过程中调整延迟。
