### ISSUE TITLE
申请补充事件类型

### ISSUE THREAD

**Issue by hatsuyuki2333** [Horiztar/Cylheim-Windows#15]
CytusII中，游玩边界和判定线可以分别隐藏（看Devillic Sphere的Crash谱面就能看出来），Cylheim只能一并隐藏或出现。申请添加支持。

**Comment by Horiztar** [comment]
Cylheim 中的播放完全支持 boundary line 和 scanline 分别隐藏，请检查谱面设计是否正确。

**Comment by hatsuyuki2333** [comment]
是我设置错了，具体隐藏是没有问题的
不好意思
