### ISSUE TITLE
[Bug Report]1.6.1.0 音符打击音效失效

### ISSUE THREAD

**Issue by Jonuarl-Reden** [Horiztar/Cylheim-Windows#6]
详细内容：从1.5.0升级为1.6.1.0后，音符打击音效无法在编辑器/播放器内播放。（已解决，见下）
已尝试操作：

- 调节右下角的音量
  - 无效，在音乐音量0%、音效音量100%的情况下播放效果等同于静音。
- 使用播放器而不是编辑器播放谱面
  - 无效，同时“打击音效”选项无实际作用。
- 检查“TapFX.wav”是否在正确的位置
  - 目前该文件在“程序目录/Resources”下。
- 调整“Hold 音符开始时播放打击音效”选项
  - 无效。
- 检查更新
  - 目前版本（1.6.1.0）为最新版。
- 重启电脑
  - 无效，包括关机后重开机。
- 替换TapFX
  - 在将原TapFX移出“程序目录/Resources”并重启Cylheim后，原有打击音效可正常播放，问题解决。

未尝试操作：

- 全新安装Cylheim
- 移动Cylheim文件夹所在目录
- 回退至1.5.0版本
  - 由于Cylheim仓库目前只剩下最新版，此操作无法进行。

其他可能有用的信息：
使用系统：Windows 10 企业版（21H1，19043.1023）
CPU：Intel(R) Core(TM) i3-4030U CPU @ 1.90GHz   1.90 GHz
RAM：8.00 GB

**Comment by Horiztar** [comment]
下个版本会解决外置tapfx无效的问题
