### ISSUE TITLE
[Bug Report] Cylheim 1.7.4.0复制/剪切的文字不能被Windows 10剪切板（由Win+V快捷键调出）读取

### ISSUE THREAD

**Issue by Jonuarl-Reden** [Horiztar/Cylheim-Windows#8]
**具体表现：**
如标题，在编辑曲目信息/延迟时复制/剪切的文字不能被“由Win+V快捷键调出的”Windows 10剪切板读取，也即，在该剪切板内没有在Cylheim 1.7.4.0内复制/剪切的文字，包括色号。

**已采取的措施：**

- 重启电脑
  - 无效。
- 检查潜在的占用剪切板的程序
  - 关闭IDM的接管选项后原问题解决，重新开启接管选项后问题未复现。

**可能有用但未采取的措施：**

- 回退Cylheim版本

**其他信息：**
操作系统版本：Windows 10 企业版 21H1 (19043.1052)

**Comment by Horiztar** [comment]
未能复现，尝试检查是否其他软件接管了剪贴板
